export const PRODUCT_STATUS = ["DRAFT", "PUBLISHED", "ARCHIVED"];
export const CONTENT_STATUS = ["DRAFT", "PUBLISHED"];
export const ORDER_STATUS = [
  "UNPAID",
  "PROCESSING",
  "SHIPPING",
  "COMPLETED",
  "CANCELLED",
  "RETURNED",
];
export const PAYMENT_STATUS = ["PENDING", "PAID", "FAILED", "REFUNDED"];
export const SHIPMENT_STATUS = ["PENDING", "SHIPPED", "DELIVERED", "FAILED", "RETURNED"];
export const DISCOUNT_TYPES = ["PERCENT", "FIXED", "FREE_SHIP"];
export const CONTACT_STATUS = ["NEW", "HANDLED", "CLOSED"];
export const BANNER_POSITIONS = ["HOME_HERO", "HOME_CATEGORY", "HOME_PROMO"];

const seo = true;

export const resources = {
  products: {
    title: "Sản phẩm",
    description: "Quản lý catalog Product, giá, publish, SEO và media.",
    endpoint: "/admin/products",
    detailPath: "/admin/products",
    searchable: true,
    filters: [
      { name: "status", label: "Trạng thái", options: PRODUCT_STATUS },
      { name: "category", label: "Category ID" },
    ],
    columns: [
      { label: "Tên", accessor: "name" },
      { label: "SKU", accessor: "sku" },
      { label: "Loại", accessor: "type", type: "status" },
      { label: "Giá", accessor: "price", type: "money" },
      { label: "Trạng thái", accessor: "status", type: "status" },
      { label: "Đã bán", accessor: "soldCount" },
    ],
    fields: [
      { name: "type", label: "Loại sản phẩm", type: "select", options: ["SET", "SINGLE"], required: true },
      { name: "categoryId", label: "Category ID", required: true },
      { name: "name", label: "Tên sản phẩm", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "sku", label: "SKU", required: true, description: "Lưu dạng VG-DT001, không kèm MSP:" },
      { name: "shortDescription", label: "Mô tả ngắn", type: "textarea", rows: 3, fullWidth: true },
      { name: "description", label: "Nội dung chi tiết", type: "textarea", rows: 8, fullWidth: true },
      { name: "price", label: "Giá bán", type: "money", required: true, min: 0 },
      { name: "compareAtPrice", label: "Giá gốc", type: "money", min: 0 },
      { name: "soldCount", label: "Đã bán", type: "number", min: 0 },
      { name: "status", label: "Trạng thái", type: "select", options: PRODUCT_STATUS },
      { name: "isFeatured", label: "Nổi bật", type: "boolean" },
    ],
    defaults: { type: "SINGLE", status: "DRAFT", soldCount: 0, isFeatured: false },
    seo,
    publishable: true,
  },
  categories: {
    title: "Danh mục",
    description: "Quản lý cây danh mục, ảnh đại diện và SEO danh mục.",
    endpoint: "/admin/categories",
    searchable: true,
    columns: [
      { label: "Tên", accessor: "name" },
      { label: "Slug", accessor: "slug" },
      { label: "Parent", accessor: "parentId" },
      { label: "Active", accessor: "isActive", type: "boolean" },
      { label: "Thứ tự", accessor: "sortOrder" },
    ],
    fields: [
      { name: "parentId", label: "Parent ID" },
      { name: "name", label: "Tên danh mục", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "description", label: "Mô tả", type: "textarea", fullWidth: true },
      { name: "imageId", label: "Ảnh", type: "media", fullWidth: true },
      { name: "sortOrder", label: "Thứ tự", type: "number" },
      { name: "isActive", label: "Đang hoạt động", type: "boolean" },
    ],
    defaults: { sortOrder: 0, isActive: true },
    seo,
  },
  coupons: {
    title: "Coupon",
    description: "Quản lý mã giảm giá theo phần trăm, số tiền cố định hoặc freeship.",
    endpoint: "/admin/coupons",
    searchable: true,
    columns: [
      { label: "Code", accessor: "code" },
      { label: "Loại", accessor: "discountType", type: "status" },
      { label: "Giá trị", accessor: "discountValue" },
      { label: "Đã dùng", accessor: "usedCount" },
      { label: "Active", accessor: "isActive", type: "boolean" },
    ],
    fields: [
      { name: "code", label: "Mã coupon", required: true },
      { name: "description", label: "Mô tả", type: "textarea", fullWidth: true },
      { name: "discountType", label: "Loại giảm", type: "select", options: DISCOUNT_TYPES, required: true },
      { name: "discountValue", label: "Giá trị", type: "number", required: true, min: 0 },
      { name: "minOrderAmount", label: "Đơn tối thiểu", type: "money", min: 0 },
      { name: "maxDiscountAmount", label: "Giảm tối đa", type: "money", min: 0 },
      { name: "usageLimit", label: "Giới hạn tổng", type: "number", min: 0 },
      { name: "usageLimitPerUser", label: "Giới hạn/user", type: "number", min: 0 },
      { name: "startsAt", label: "Bắt đầu", type: "date" },
      { name: "endsAt", label: "Kết thúc", type: "date" },
      { name: "isActive", label: "Đang hoạt động", type: "boolean" },
    ],
    defaults: { discountType: "PERCENT", discountValue: 10, isActive: true },
  },
  orders: {
    title: "Đơn hàng",
    description: "Theo dõi đơn hàng, snapshot khách hàng và vòng đời giao vận.",
    endpoint: "/admin/orders",
    detailPath: "/admin/orders",
    searchable: true,
    readOnlyCreate: true,
    noDelete: true,
    filters: [
      { name: "status", label: "Trạng thái", options: ORDER_STATUS },
      { name: "paymentStatus", label: "Thanh toán", options: PAYMENT_STATUS },
    ],
    columns: [
      { label: "Mã đơn", accessor: "orderNumber" },
      { label: "Khách hàng", accessor: "customerName" },
      { label: "Phone", accessor: "customerPhone" },
      { label: "Tổng", accessor: "totalAmount", type: "money" },
      { label: "Status", accessor: "status", type: "status" },
      { label: "Payment", accessor: "paymentStatus", type: "status" },
      { label: "Ngày đặt", accessor: "placedAt", type: "date" },
    ],
    fields: [
      { name: "status", label: "Status", type: "select", options: ORDER_STATUS },
    ],
  },
  news: {
    title: "Tin tức",
    description: "Quản lý NewsArticle, cover, nội dung, publishedAt và SEO.",
    endpoint: "/admin/news",
    searchable: true,
    columns: [
      { label: "Tiêu đề", accessor: "title" },
      { label: "Slug", accessor: "slug" },
      { label: "Category", accessor: "category.name" },
      { label: "Status", accessor: "status", type: "status" },
      { label: "Lượt xem", accessor: "viewCount" },
    ],
    fields: [
      { name: "categoryId", label: "News category ID", required: true },
      { name: "title", label: "Tiêu đề", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "excerpt", label: "Excerpt", type: "textarea", rows: 3, fullWidth: true },
      { name: "content", label: "Nội dung", type: "textarea", rows: 10, fullWidth: true, required: true },
      { name: "coverImageId", label: "Cover image", type: "media", fullWidth: true },
      { name: "status", label: "Trạng thái", type: "select", options: CONTENT_STATUS },
      { name: "publishedAt", label: "Ngày xuất bản", type: "date" },
    ],
    defaults: { status: "DRAFT" },
    seo,
    auxiliary: {
      title: "Danh mục tin tức",
      endpoint: "/admin/news/categories",
      columns: [
        { label: "Tên", accessor: "name" },
        { label: "Slug", accessor: "slug" },
        { label: "Thứ tự", accessor: "sortOrder" },
      ],
      fields: [
        { name: "name", label: "Tên danh mục", required: true },
        { name: "slug", label: "Slug", required: true },
        { name: "sortOrder", label: "Thứ tự", type: "number" },
      ],
      defaults: { sortOrder: 0 },
    },
  },
  pages: {
    title: "Trang CMS",
    description: "Quản lý Page dạng block JSON cho about, showroom, policy, factory.",
    endpoint: "/admin/pages",
    searchable: true,
    columns: [
      { label: "Key", accessor: "key" },
      { label: "Title", accessor: "title" },
      { label: "Slug", accessor: "slug" },
      { label: "Status", accessor: "status", type: "status" },
    ],
    fields: [
      { name: "key", label: "Key", required: true },
      { name: "title", label: "Tiêu đề", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "content", label: "Content JSON", type: "json", fullWidth: true, rows: 12 },
      { name: "status", label: "Trạng thái", type: "select", options: CONTENT_STATUS },
    ],
    defaults: { status: "DRAFT", content: "{}" },
    seo,
  },
  faq: {
    title: "FAQ",
    description: "Quản lý câu hỏi thường gặp.",
    endpoint: "/admin/faq",
    columns: [
      { label: "Câu hỏi", accessor: "question" },
      { label: "Nhóm", accessor: "category" },
      { label: "Active", accessor: "isActive", type: "boolean" },
      { label: "Thứ tự", accessor: "sortOrder" },
    ],
    fields: [
      { name: "question", label: "Câu hỏi", required: true, fullWidth: true },
      { name: "answer", label: "Câu trả lời", type: "textarea", rows: 6, required: true, fullWidth: true },
      { name: "category", label: "Nhóm" },
      { name: "sortOrder", label: "Thứ tự", type: "number" },
      { name: "isActive", label: "Đang hiển thị", type: "boolean" },
    ],
    defaults: { isActive: true, sortOrder: 0 },
  },
  gallery: {
    title: "Thư viện hình ảnh",
    description: "Quản lý hình ảnh hiển thị ở trang gallery.",
    endpoint: "/admin/gallery",
    columns: [
      { label: "Title", accessor: "title" },
      { label: "Category", accessor: "category" },
      { label: "Media", accessor: "mediaId" },
      { label: "Active", accessor: "isActive", type: "boolean" },
    ],
    fields: [
      { name: "mediaId", label: "Media", type: "media", required: true, fullWidth: true },
      { name: "title", label: "Title" },
      { name: "category", label: "Category" },
      { name: "sortOrder", label: "Thứ tự", type: "number" },
      { name: "isActive", label: "Đang hiển thị", type: "boolean" },
    ],
    defaults: { sortOrder: 0, isActive: true },
  },
  showrooms: {
    title: "Showroom",
    description: "Quản lý showroom, map, giờ mở cửa và ảnh liên quan.",
    endpoint: "/admin/showrooms",
    columns: [
      { label: "Tên", accessor: "name" },
      { label: "Địa chỉ", accessor: "address" },
      { label: "Phone", accessor: "phone" },
      { label: "Active", accessor: "isActive", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Tên showroom", required: true },
      { name: "phone", label: "Điện thoại" },
      { name: "address", label: "Địa chỉ", type: "textarea", rows: 3, required: true, fullWidth: true },
      { name: "mapEmbedUrl", label: "Map embed URL", type: "url", fullWidth: true },
      { name: "openingHours", label: "Giờ mở cửa" },
      { name: "sortOrder", label: "Thứ tự", type: "number" },
      { name: "isActive", label: "Đang hoạt động", type: "boolean" },
    ],
    defaults: { sortOrder: 0, isActive: true },
  },
  banners: {
    title: "Banner",
    description: "Quản lý banner trang chủ/category/promo.",
    endpoint: "/admin/banners",
    columns: [
      { label: "Title", accessor: "title" },
      { label: "Position", accessor: "position", type: "status" },
      { label: "Link", accessor: "linkUrl" },
      { label: "Active", accessor: "isActive", type: "boolean" },
    ],
    fields: [
      { name: "title", label: "Title" },
      { name: "imageId", label: "Image", type: "media", required: true, fullWidth: true },
      { name: "linkUrl", label: "Link URL" },
      { name: "position", label: "Vị trí", type: "select", options: BANNER_POSITIONS, required: true },
      { name: "sortOrder", label: "Thứ tự", type: "number" },
      { name: "isActive", label: "Đang hiển thị", type: "boolean" },
      { name: "startsAt", label: "Bắt đầu", type: "date" },
      { name: "endsAt", label: "Kết thúc", type: "date" },
    ],
    defaults: { position: "HOME_HERO", sortOrder: 0, isActive: true },
  },
  redirects: {
    title: "Redirects",
    description: "Quản lý 301/302 redirect cho SEO khi đổi slug.",
    endpoint: "/admin/redirects",
    columns: [
      { label: "From", accessor: "fromPath" },
      { label: "To", accessor: "toPath" },
      { label: "Code", accessor: "statusCode" },
      { label: "Hits", accessor: "hitCount" },
      { label: "Active", accessor: "isActive", type: "boolean" },
    ],
    fields: [
      { name: "fromPath", label: "From path", required: true },
      { name: "toPath", label: "To path", required: true },
      { name: "statusCode", label: "Status code", type: "select", options: [301, 302] },
      { name: "isActive", label: "Đang hoạt động", type: "boolean" },
    ],
    defaults: { statusCode: 301, isActive: true },
  },
  contactLeads: {
    title: "Liên hệ",
    description: "Quản lý lead từ form liên hệ.",
    endpoint: "/admin/contact-leads",
    readOnlyCreate: true,
    noDelete: true,
    columns: [
      { label: "Tên", accessor: "name" },
      { label: "Phone", accessor: "phone" },
      { label: "Email", accessor: "email" },
      { label: "Status", accessor: "status", type: "status" },
      { label: "Ngày gửi", accessor: "createdAt", type: "date" },
    ],
    fields: [
      { name: "status", label: "Trạng thái", type: "select", options: CONTACT_STATUS },
      { name: "handledById", label: "Handled by user ID" },
    ],
    defaults: { status: "NEW" },
  },
  newsletter: {
    title: "Newsletter",
    description: "Danh sách email đăng ký nhận tin. Endpoint hiện tại chỉ hỗ trợ list.",
    endpoint: "/newsletter/subscribers",
    readOnlyCreate: true,
    noDelete: true,
    columns: [
      { label: "Email", accessor: "email" },
      { label: "Active", accessor: "isActive", type: "boolean" },
      { label: "Ngày đăng ký", accessor: "createdAt", type: "date" },
    ],
    fields: [],
  },
};
